name: mira_widgets
description: "Fluent extension-based API for Flutter widgets. Chain methods to build UIs faster with less boilerplate."
version: 0.0.5
homepage: 
repository: https://github.com/Okikday/mira_widgets

exclude:
  - android/**
  - ios/**
  - web/**
  - build/**
  - test/**

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

